# Generated by Django 6.0 on 2025-12-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0002_alter_task_datecompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_cedula', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('licencia_conducir', models.CharField(max_length=50)),
                ('telefono_convencional', models.CharField(max_length=20)),
                ('telefono_fijo', models.CharField(max_length=20)),
                ('direccion_trabajo', models.CharField(max_length=150)),
                ('direccion_domiciliaria', models.CharField(max_length=150)),
                ('sitio_web', models.URLField(blank=True)),
            ],
        ),
    ]
