# Generated by Django 6.0 on 2025-12-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0004_datospersonales_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
