# Generated by Django 6.0 on 2025-12-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0005_datospersonales_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direccion_domiciliaria',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direccion_trabajo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licencia_conducir',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numero_cedula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono_convencional',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
