# Generated by Django 6.0 on 2025-12-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0006_alter_datospersonales_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
