# Generated by Django 6.0 on 2025-12-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0007_datospersonales_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
