# Generated by Django 6.0 on 2025-12-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0008_alter_datospersonales_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
