# Generated by Django 6.0 on 2025-12-20 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0009_alter_datospersonales_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_empresa_trabajadas', models.CharField(blank=True, max_length=100)),
                ('cargos_de_trabajo', models.CharField(blank=True, max_length=100)),
                ('lugar_empresa_trabajada', models.CharField(blank=True, max_length=100)),
                ('email_de_empresa', models.CharField(blank=True, max_length=100)),
                ('sitio_web_empresa', models.URLField(blank=True)),
                ('nombre_contacto_empresarial', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto_empresarial', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio_gestion', models.DateField(blank=True, null=True)),
                ('fecha_fin_gestion', models.DateField(blank=True, null=True)),
                ('descripcion_funciones', models.CharField(blank=True, max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-fecha_inicio_gestion'],
            },
        ),
    ]
