# Generated by Django 6.0 on 2025-12-20 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0010_alter_datospersonales_descripcion_experiencialaboral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reconocimiento', models.CharField(blank=True, max_length=100)),
                ('fecha_reconocimiento', models.DateField(blank=True, null=True)),
                ('descripcion_reconocimiento', models.TextField(blank=True, max_length=1000)),
                ('entidad_patrocinada', models.CharField(blank=True, max_length=100)),
                ('nombre_contacto_auspicia', models.CharField(blank=True, max_length=100)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimiento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
