# Generated by Django 6.0 on 2025-12-21 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0011_reconocimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('total_horas', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('entidad_patrocinadora', models.CharField(blank=True, max_length=100)),
                ('nombre_contacto_auspicia', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto_auspicia', models.CharField(blank=True, max_length=60)),
                ('email_empresa_patrocinadora', models.EmailField(blank=True, max_length=60)),
                ('mostrar_en_front', models.BooleanField(default=True)),
                ('ruta_certificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('mostrar_en_front', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('fecha_producto', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('mostrar_en_front', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
