# Generated by Django 6.0 on 2025-12-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0012_cursorealizado_productoacademico_productolaboral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoacademico',
            name='clasificador',
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='fecha_producto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
