# Generated by Django 6.0 on 2025-12-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginausuario', '0013_remove_productoacademico_clasificador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoacademico',
            name='proyectoacademico',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='proyectolaboral',
            field=models.URLField(blank=True),
        ),
    ]
